# Generated by Django 4.1.3 on 2023-01-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pdet',
            new_name='que',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
