# Generated by Django 4.1.3 on 2023-01-18 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0002_rename_pdet_post_que_remove_post_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
