# Generated by Django 4.1.3 on 2023-01-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0003_alter_post_date_alter_post_time_alter_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
