# Generated by Django 4.1.3 on 2023-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0004_post_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(),
        ),
    ]
