# Generated by Django 4.1.3 on 2023-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(),
        ),
    ]
