# Generated by Django 4.1.3 on 2023-01-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examate', '0008_alter_post_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
